// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WeatherAPIClient is an autogenerated mock type for the WeatherAPIClient type
type WeatherAPIClient struct {
	mock.Mock
}

// GetTemperature provides a mock function with given fields: city
func (_m *WeatherAPIClient) GetTemperature(city string) (float64, error) {
	ret := _m.Called(city)

	if len(ret) == 0 {
		panic("no return value specified for GetTemperature")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return rf(city)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(city)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWeatherAPIClient creates a new instance of WeatherAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherAPIClient {
	mock := &WeatherAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
